import type { Product } from "@/types/product";

// ponytail: the small catalog stays local; move these queries to Neon when
// inventory needs persistence. Product pages keep the same async API.
const catalog: Product[] = [
  {
    id: "sage-stand-mixer",
    name: "Sage Stand Mixer",
    description: "A 4.5L tilt-head mixer with a brushed-steel bowl, wire whisk, and six-speed control. A locking bowl base, easy-grip handle, and rubber feet keep everyday baking steady.",
    category: "Kitchen appliances",
    image: "/products/sage-stand-mixer.webp",
    price: 249,
  },
  {
    id: "digital-rice-cooker",
    name: "Digital Rice Cooker",
    description: "A 1.8L rice cooker with a removable non-stick pot, digital cooking timer, and keep-warm mode. A hinged lid, steam-release vent, and carry handle make serving simple.",
    category: "Kitchen appliances",
    image: "/products/digital-rice-cooker.webp",
    price: 79,
  },
  {
    id: "compact-food-processor",
    name: "Compact Food Processor",
    description: "A 2L clear work bowl with stainless-steel chopping blades, a feed tube, and pulse control. Volume markings, an easy-grip handle, and an interlocking lid help with everyday prep.",
    category: "Kitchen appliances",
    image: "/products/compact-food-processor.webp",
    price: 99,
  },
  {
    id: "belgian-waffle-maker",
    name: "Belgian Waffle Maker",
    description: "Deep-grid non-stick plates for two Belgian-style waffles, with adjustable browning and ready lights. A hinged cream housing and cool-touch handle keep breakfast uncomplicated.",
    category: "Kitchen appliances",
    image: "/products/belgian-waffle-maker.webp",
    price: 59,
  },
  {
    id: "stovetop-moka-pot",
    name: "Stovetop Moka Pot",
    description: "A six-cup aluminium moka pot with a faceted boiler, hinged lid, and heat-resistant handle. A brass safety valve and tapered spout finish this stovetop classic; not for induction.",
    category: "Cookware",
    image: "/products/stovetop-moka-pot.webp",
    price: 39,
  },
  {
    id: "fluted-baking-dish",
    name: "Fluted Baking Dish",
    description: "A 32cm cream ceramic oven dish with fluted walls, a generous rolled rim, and integrated handles. The softly speckled glaze takes roasted vegetables and baked pasta straight to the table.",
    category: "Cookware",
    image: "/products/fluted-baking-dish.webp",
    price: 32,
  },
  {
    id: "stainless-colander",
    name: "Stainless Steel Colander",
    description: "A 24cm brushed-steel colander with fine drainage holes, a rolled rim, and two riveted handles. A raised foot ring keeps rinsed produce clear of the sink.",
    category: "Cookware",
    image: "/products/stainless-colander.webp",
    price: 24,
  },
  {
    id: "acacia-knife-block",
    name: "Acacia Knife Block Set",
    description: "Five stainless-steel knives—chef's, bread, santoku, utility, and paring—in a grained acacia block. Riveted handles, polished bolsters, and angled slots keep the daily tools organised.",
    category: "Cookware",
    image: "/products/acacia-knife-block.webp",
    price: 89,
  },
  {
    id: "countertop-dish-rack",
    name: "Countertop Dish Rack",
    description: "A two-level wire dish drainer with plate slots, a removable utensil cup, and a ribbed tray with a pouring spout. Rubber feet protect the worktop. Tableware not included.",
    category: "Cleaning",
    image: "/products/countertop-dish-rack.webp",
    price: 45,
  },
  {
    id: "bamboo-dustpan-set",
    name: "Bamboo Dustpan & Brush",
    description: "A compact bamboo dustpan and matching hand brush with dense bristles, a flexible rubber lip, and a hanging loop. Warm wood grain makes the quick sweep feel less like a chore.",
    category: "Cleaning",
    image: "/products/bamboo-dustpan-set.webp",
    price: 19,
  },
  {
    id: "refillable-soap-dispenser",
    name: "Refillable Soap Dispenser",
    description: "A 400ml ribbed ceramic dispenser with a polished-metal pump, screw-on collar, and gently speckled cream glaze. Refill with liquid hand soap and keep the sink area tidy.",
    category: "Cleaning",
    image: "/products/refillable-soap-dispenser.webp",
    price: 22,
  },
  {
    id: "rechargeable-fabric-shaver",
    name: "Rechargeable Fabric Shaver",
    description: "A USB-C rechargeable fabric shaver with a perforated steel head, removable lint chamber, and comfortable grip. Refresh suitable knitwear with a light touch; test a hidden area first.",
    category: "Laundry",
    image: "/products/rechargeable-fabric-shaver.webp",
    price: 29,
  },
  {
    id: "wooden-hanger-set",
    name: "Wooden Hanger Set",
    description: "Six beechwood hangers with curved shoulders, trouser bars, and brushed-metal swivel hooks. Shoulder notches and smooth natural grain help keep the wardrobe in good order.",
    category: "Laundry",
    image: "/products/wooden-hanger-set.webp",
    price: 25,
  },
  {
    id: "compartment-laundry-sorter",
    name: "Two-Compartment Laundry Sorter",
    description: "A bamboo frame holds two removable 40L linen bags for lights and darks. Open tops, stitched carry handles, and capped feet make sorting and moving the next load straightforward.",
    category: "Laundry",
    image: "/products/compartment-laundry-sorter.webp",
    price: 69,
  },
  {
    id: "rotating-spice-rack",
    name: "Rotating Spice Rack",
    description: "Twelve refillable glass jars with metal screw lids on a two-tier wood-and-steel turntable. Labelled fronts keep favourite seasonings easy to reach. Spices not included.",
    category: "Storage",
    image: "/products/rotating-spice-rack.webp",
    price: 49,
  },
  {
    id: "airtight-food-container-set",
    name: "Airtight Food Container Set",
    description: "Four clear pantry containers in 500ml, 900ml, 1.4L, and 2L sizes, with clip-lock lids and silicone gaskets. Stackable shapes bring order to dry ingredients. Food not included.",
    category: "Storage",
    image: "/products/airtight-food-container-set.webp",
    price: 35,
  },
  {
    id: "woven-storage-ottoman",
    name: "Woven Storage Ottoman",
    description: "A 45cm woven ottoman with a removable, linen-padded lid and low wooden feet. A textured seat for the living room, with a concealed compartment for throws and everyday extras.",
    category: "Storage",
    image: "/products/woven-storage-ottoman.webp",
    price: 89,
  },
  {
    id: "digital-dehumidifier",
    name: "Digital Dehumidifier",
    description: "A compact dehumidifier rated up to 12L per day, with a 2L removable tank, adjustable humidity target, and full-tank shut-off. A digital display and castors make room-to-room use simple.",
    category: "Home comfort",
    image: "/products/digital-dehumidifier.webp",
    price: 159,
  },
  {
    id: "ribbed-ceramic-diffuser",
    name: "Ribbed Ceramic Diffuser",
    description: "A 150ml ultrasonic aroma diffuser with a fluted sage ceramic cover, wood-grain base, and automatic shut-off when empty. Add a few drops of suitable essential oil; oil not included.",
    category: "Home comfort",
    image: "/products/ribbed-ceramic-diffuser.webp",
    price: 39,
  },
  {
    id: "adjustable-reading-lamp",
    name: "Adjustable Reading Lamp",
    description: "An articulated cream reading lamp with tension springs, adjustable pivots, and a warm-white LED diffuser. A weighted base and fabric-wrapped cord finish a focused little pool of light.",
    category: "Home comfort",
    image: "/products/adjustable-reading-lamp.webp",
    price: 69,
  },
  {
    id: "sage-air-fryer",
    name: "Sage Air Fryer",
    description: "A 5L countertop air fryer with a digital timer, adjustable temperature up to 200°C, and a removable non-stick basket. Crisp dinners, less fuss.",
    category: "Kitchen appliances",
    image: "/products/sage-air-fryer.webp",
    price: 119,
  },
  {
    id: "cream-electric-kettle",
    name: "Cream Electric Kettle",
    description: "A 1.7L kettle with a stainless-steel interior, easy-pour spout, 360° base, and automatic shut-off. A softer start to your morning.",
    category: "Kitchen appliances",
    image: "/products/cream-electric-kettle.webp",
    price: 49,
  },
  {
    id: "two-slice-toaster",
    name: "Two-Slice Toaster",
    description: "Wide slots for sourdough, six browning settings, and a removable crumb tray. Finished in warm cream with brushed-metal details.",
    category: "Kitchen appliances",
    image: "/products/two-slice-toaster.webp",
    price: 59,
  },
  {
    id: "compact-espresso-machine",
    name: "Compact Espresso Machine",
    description: "A compact 15-bar espresso machine with a steam wand, removable drip tray, and 1.2L water tank. Your daily coffee ritual, at home.",
    category: "Kitchen appliances",
    image: "/products/compact-espresso-machine.webp",
    price: 189,
  },
  {
    id: "glass-jug-blender",
    name: "Glass Jug Blender",
    description: "A 1.5L glass jug, stainless-steel blades, and three speeds with pulse control. Blend smoothies, sauces, and soups once cooled.",
    category: "Kitchen appliances",
    image: "/products/glass-jug-blender.webp",
    price: 69,
  },
  {
    id: "cast-iron-casserole",
    name: "Cast Iron Casserole",
    description: "A 4L enamelled cast-iron casserole in warm terracotta. A close-fitting lid and generous handles take slow-cooked meals from hob to table.",
    category: "Cookware",
    image: "/products/cast-iron-casserole.webp",
    price: 79,
  },
  {
    id: "ceramic-frying-pan",
    name: "Ceramic Frying Pan",
    description: "A 28cm frying pan with a smooth ceramic cooking surface, sage exterior, and comfortable wood handle. Made for everyday hob cooking; hand-wash only.",
    category: "Cookware",
    image: "/products/ceramic-frying-pan.webp",
    price: 39,
  },
  {
    id: "stainless-saucepan",
    name: "Stainless Steel Saucepan",
    description: "A 2L stainless-steel saucepan with a fitted lid, long handle, and layered base for even heating. For sauces, grains, and smaller portions.",
    category: "Cookware",
    image: "/products/stainless-saucepan.webp",
    price: 45,
  },
  {
    id: "bamboo-chopping-board",
    name: "Bamboo Chopping Board",
    description: "A 40 × 28cm bamboo prep board with a juice groove and carry handle. A warm, hard-wearing surface for chopping and serving; hand-wash and dry upright.",
    category: "Cookware",
    image: "/products/bamboo-chopping-board.webp",
    price: 24,
  },
  {
    id: "stoneware-dinner-set",
    name: "Stoneware Dinner Set",
    description: "Twelve pieces for four people: four dinner plates, four bowls, and four mugs. Warm cream stoneware with a softly glazed finish.",
    category: "Cookware",
    image: "/products/stoneware-dinner-set.webp",
    price: 64,
  },
  {
    id: "cordless-stick-vacuum",
    name: "Cordless Stick Vacuum",
    description: "A lightweight rechargeable vacuum with a motorised floor head, washable filter, and removable dust cup. Up to 40 minutes of cleaning in standard mode.",
    category: "Cleaning",
    image: "/products/cordless-stick-vacuum.webp",
    price: 159,
  },
  {
    id: "robot-vacuum",
    name: "Robot Vacuum",
    description: "A low-profile robot vacuum with room mapping, edge brushes, and automatic return to its charging dock. A little help keeping everyday dust under control.",
    category: "Cleaning",
    image: "/products/robot-vacuum.webp",
    price: 229,
  },
  {
    id: "spray-mop",
    name: "Refillable Spray Mop",
    description: "A slim spray mop with a 500ml refillable bottle, swivel head, and washable microfibre pad. For quick clean-ups on sealed hard floors.",
    category: "Cleaning",
    image: "/products/spray-mop.webp",
    price: 29,
  },
  {
    id: "steam-cleaner",
    name: "Compact Steam Cleaner",
    description: "A portable 1L steam cleaner with a flexible hose and detail nozzle. Loosen grime on sealed tiles and suitable hard surfaces without detergent.",
    category: "Cleaning",
    image: "/products/steam-cleaner.webp",
    price: 89,
  },
  {
    id: "pedal-bin",
    name: "Soft-Close Pedal Bin",
    description: "A 30L cream bin with a soft-closing lid, foot pedal, and removable inner bucket. A clean-lined essential that keeps hands free.",
    category: "Cleaning",
    image: "/products/pedal-bin.webp",
    price: 49,
  },
  {
    id: "steam-iron",
    name: "Everyday Steam Iron",
    description: "A 2,400W steam iron with a pointed soleplate, variable steam, and an easy-fill water tank. Adjustable heat for your garment's care label.",
    category: "Laundry",
    image: "/products/steam-iron.webp",
    price: 45,
  },
  {
    id: "handheld-garment-steamer",
    name: "Handheld Garment Steamer",
    description: "A compact steamer with a removable 250ml water tank and comfortable grip. Refresh hanging garments and soften creases without setting up a board.",
    category: "Laundry",
    image: "/products/handheld-garment-steamer.webp",
    price: 39,
  },
  {
    id: "folding-drying-rack",
    name: "Folding Drying Rack",
    description: "An airy, freestanding drying rack with fold-out wings and 18m of hanging space. Folds flat between wash days, with capped feet to protect floors.",
    category: "Laundry",
    image: "/products/folding-drying-rack.webp",
    price: 49,
  },
  {
    id: "woven-laundry-hamper",
    name: "Woven Laundry Hamper",
    description: "A 60L woven hamper with a fitted lid, carry handles, and removable cotton liner. Natural texture that keeps the wash-day pile out of sight.",
    category: "Laundry",
    image: "/products/woven-laundry-hamper.webp",
    price: 35,
  },
  {
    id: "ironing-board",
    name: "Folding Ironing Board",
    description: "A 110 × 34cm padded board with adjustable height, a cotton cover, and a metal iron rest. Folds away neatly when the last shirt is done.",
    category: "Laundry",
    image: "/products/ironing-board.webp",
    price: 59,
  },
  {
    id: "glass-storage-jars",
    name: "Glass Storage Jars",
    description: "Three clear glass pantry jars in 600ml, 900ml, and 1.2L sizes. Bamboo lids with silicone seals keep dry ingredients tidy and easy to find.",
    category: "Storage",
    image: "/products/glass-storage-jars.webp",
    price: 29,
  },
  {
    id: "bamboo-bread-box",
    name: "Bamboo Bread Box",
    description: "A warm bamboo bread box with a smooth roll-top door and easy-grip handle. Keep loaves and pastries together without crowding the worktop.",
    category: "Storage",
    image: "/products/bamboo-bread-box.webp",
    price: 39,
  },
  {
    id: "stackable-storage-baskets",
    name: "Stackable Storage Baskets",
    description: "A set of three ventilated baskets with carry handles and stackable rims. Sort pantry staples, bathroom essentials, or the things that never have a home.",
    category: "Storage",
    image: "/products/stackable-storage-baskets.webp",
    price: 25,
  },
  {
    id: "modular-drawer-organiser",
    name: "Bamboo Drawer Organiser",
    description: "Five open bamboo trays in complementary sizes. Arrange them to bring a little order to cutlery, utensils, stationery, or everyday odds and ends.",
    category: "Storage",
    image: "/products/modular-drawer-organiser.webp",
    price: 19,
  },
  {
    id: "kitchen-storage-trolley",
    name: "Three-Tier Storage Trolley",
    description: "A slim three-tier metal trolley with raised tray edges, a push handle, and four castors. Keep kitchen supplies close, then wheel them out of the way.",
    category: "Storage",
    image: "/products/kitchen-storage-trolley.webp",
    price: 69,
  },
  {
    id: "hepa-air-purifier",
    name: "HEPA Air Purifier",
    description: "A compact air purifier with a replaceable HEPA filter, three fan speeds, and a dimmable status display. Sized for bedrooms and home offices up to 25m².",
    category: "Home comfort",
    image: "/products/hepa-air-purifier.webp",
    price: 129,
  },
  {
    id: "oscillating-table-fan",
    name: "Oscillating Table Fan",
    description: "A 30cm sage desk fan with three speeds, an adjustable tilt, and side-to-side oscillation. A weighted base keeps the breeze steady.",
    category: "Home comfort",
    image: "/products/oscillating-table-fan.webp",
    price: 49,
  },
  {
    id: "ceramic-space-heater",
    name: "Ceramic Space Heater",
    description: "A compact 1,500W ceramic heater with two heat settings, a carry handle, and tip-over protection. For supervised use on a clear, level floor.",
    category: "Home comfort",
    image: "/products/ceramic-space-heater.webp",
    price: 59,
  },
  {
    id: "ultrasonic-humidifier",
    name: "Ultrasonic Humidifier",
    description: "A 2L cool-mist humidifier with adjustable output, an easy-clean tank, and automatic shut-off when empty. Quiet comfort for your bedside or desk.",
    category: "Home comfort",
    image: "/products/ultrasonic-humidifier.webp",
    price: 45,
  },
  {
    id: "dome-table-lamp",
    name: "Dome Table Lamp",
    description: "A sculptural terracotta dome lamp with a warm-white LED light and in-line switch. A soft pool of light for reading corners and bedside tables.",
    category: "Home comfort",
    image: "/products/dome-table-lamp.webp",
    price: 39,
  },
];

export async function getProducts(query?: string): Promise<Product[]> {
  const q = query?.trim().toLowerCase();

  if (!q) return catalog;

  return catalog.filter((p) =>
    `${p.name} ${p.description} ${p.category}`.toLowerCase().includes(q),
  );
}

export async function getProduct(id: string): Promise<Product | undefined> {
  return catalog.find((p) => p.id === id);
}
