import type { ProductDetails } from "@/types/product";

// ponytail: the detail sheet is keyed by product id and lives apart from the
// catalog, so a grid or a cart never ships the spec tables it does not render.
// Every number here is the one the product's own description states; where a
// description is silent the value is catalogue copy for this demo shop.
const sheets: Record<string, ProductDetails> = {
  "sage-stand-mixer": {
    highlights: [
      { title: "Tilt-head access", body: "The head tilts back so the 4.5L bowl can be lifted clear, scraped down or refilled without moving the mixer." },
      { title: "Six-speed control", body: "Six speeds cover slow folding of dry flour through to whipping cream with the wire whisk, set on a single dial." },
      { title: "Steady on the counter", body: "A locking bowl base and rubber feet hold the mixer in place, while the easy-grip handle helps when carrying the bowl." },
    ],
    specs: [
      { label: "Capacity", value: "4.5L" },
      { label: "Bowl", value: "Brushed steel, locking base" },
      { label: "Settings", value: "Six speeds" },
      { label: "Head", value: "Tilt-head" },
      { label: "Power", value: "800W" },
      { label: "Cord", value: "1.2m" },
    ],
    materials: ["Brushed stainless steel", "Die-cast aluminium", "Rubber"],
    inBox: ["Sage Stand Mixer", "4.5L brushed-steel bowl", "Wire whisk"],
    care: "Hand-wash the bowl and wire whisk, and wipe the motor housing with a damp cloth.",
  },
  "digital-rice-cooker": {
    highlights: [
      { title: "Removable non-stick pot", body: "The 1.8L inner pot lifts out for serving and rinsing, and the non-stick coating releases rice without scraping." },
      { title: "Timer and keep-warm", body: "A digital cooking timer starts the batch to suit a mealtime, then keep-warm mode holds the rice at serving temperature." },
      { title: "Hinged lid and vent", body: "The hinged lid stays attached while spooning out rice, and the steam-release vent lets pressure escape during cooking." },
    ],
    specs: [
      { label: "Capacity", value: "1.8L" },
      { label: "Power", value: "700W" },
      { label: "Settings", value: "Cook, digital timer, keep-warm" },
      { label: "Pot", value: "Removable non-stick" },
      { label: "Lid", value: "Hinged, with steam-release vent" },
      { label: "Dimensions", value: "26 × 26 × 24cm" },
    ],
    materials: ["Non-stick coated aluminium", "Moulded polypropylene", "Brushed stainless steel", "Tempered glass"],
    inBox: ["Digital rice cooker, 1.8L", "Removable non-stick pot", "Measuring cup and rice paddle", "Instruction leaflet"],
    care: "Hand-wash the inner pot and wipe the housing with a damp cloth; never immerse the base.",
  },
  "compact-food-processor": {
    highlights: [
      { title: "2L clear work bowl", body: "The 2L bowl holds everyday batches, and volume markings on the clear wall show how far the contents have risen." },
      { title: "Stainless-steel chopping blades", body: "Stainless-steel chopping blades handle onions, herbs and nuts, cutting prep down to a few short bursts at the bowl." },
      { title: "Feed tube and pulse", body: "The feed tube takes pieces while the motor runs, and pulse control gives short bursts for a coarser texture." },
    ],
    specs: [
      { label: "Capacity", value: "2L work bowl" },
      { label: "Blades", value: "Stainless-steel chopping blades" },
      { label: "Controls", value: "Pulse control" },
      { label: "Bowl", value: "Clear, with volume markings" },
      { label: "Lid", value: "Interlocking, with feed tube" },
      { label: "Power", value: "400W" },
    ],
    materials: ["Stainless steel", "Clear plastic", "Moulded polypropylene"],
    inBox: ["Compact food processor", "2L work bowl and lid", "Stainless-steel chopping blade", "Instruction leaflet"],
    care: "Hand-wash the bowl, lid and blade; wipe the motor base with a damp cloth only.",
  },
  "belgian-waffle-maker": {
    highlights: [
      { title: "Deep-grid plates", body: "Non-stick deep-grid plates bake two Belgian-style waffles at a time, holding the thick pockets that suit syrup or fruit." },
      { title: "Adjustable browning", body: "A browning dial sets the finish from pale to dark, so the same batter can suit different preferences at one sitting." },
      { title: "Ready lights", body: "Two indicator lights show when the plates have reached temperature and when the waffles are done, removing guesswork from timing." },
    ],
    specs: [
      { label: "Capacity", value: "Two Belgian-style waffles" },
      { label: "Plates", value: "Deep-grid non-stick" },
      { label: "Settings", value: "Adjustable browning dial" },
      { label: "Indicators", value: "Power and ready lights" },
      { label: "Housing", value: "Hinged, cream finish" },
      { label: "Power", value: "1,000W" },
    ],
    materials: ["Non-stick coated plates", "Cream finish housing", "Cool-touch handle"],
    inBox: ["Belgian waffle maker", "Instruction leaflet", "Recipe card"],
    care: "Unplug and cool before wiping the non-stick plates with a damp cloth; do not immerse.",
  },
  "stovetop-moka-pot": {
    highlights: [
      { title: "Faceted aluminium boiler", body: "The faceted boiler spreads heat from gas and electric rings evenly around the base, bringing water up to pressure without scorching the grounds." },
      { title: "Brass safety valve", body: "A brass safety valve sits in the boiler wall and releases pressure if the filter clogs, keeping the brew cycle predictable." },
      { title: "Hinged lid and spout", body: "The hinged lid stays attached while pouring and the tapered spout directs coffee into six small cups without dripping down the side." },
    ],
    specs: [
      { label: "Capacity", value: "Six cups" },
      { label: "Material", value: "Aluminium body, brass valve" },
      { label: "Boiler", value: "Faceted, eight sides" },
      { label: "Lid", value: "Hinged, heat-resistant knob" },
      { label: "Hobs", value: "Gas, electric, ceramic; not induction" },
      { label: "Weight", value: "430g" },
    ],
    materials: ["Cast aluminium", "Brass", "Heat-resistant phenolic", "Silicone"],
    inBox: ["Six-cup moka pot", "Spare silicone gasket", "Filter plate", "Instruction leaflet"],
    care: "Hand-wash in warm water without detergent, dry fully, and do not use on induction hobs.",
  },
  "fluted-baking-dish": {
    highlights: [
      { title: "Fluted ceramic walls", body: "The fluted walls add rigidity to the 32cm dish and give roasted vegetables more edge contact for browning at the sides." },
      { title: "Integrated handles", body: "Handles are formed as part of the body, so the dish can be lifted from the oven with gloved hands on both sides." },
      { title: "Rolled rim", body: "A generous rolled rim gives a secure grip when carrying baked pasta from oven to table, and keeps bubbling sauces contained." },
    ],
    specs: [
      { label: "Length", value: "32cm" },
      { label: "Material", value: "Ceramic" },
      { label: "Finish", value: "Cream speckled glaze" },
      { label: "Handles", value: "Integrated, both ends" },
      { label: "Rim", value: "Rolled" },
      { label: "Capacity", value: "3.5L" },
    ],
    materials: ["Ceramic", "Speckled glaze"],
    inBox: ["Fluted baking dish, 32cm", "Care leaflet"],
    care: "Let the dish cool before washing, and avoid setting it on a direct flame or hob.",
  },
  "stainless-colander": {
    highlights: [
      { title: "Fine drainage holes", body: "Perforations across the bowl let water run off quickly while holding back rice, pasta and small items such as berries." },
      { title: "Two riveted handles", body: "Riveted joints hold the handles firm under the weight of a full 24cm bowl, so lifting and tipping stay steady." },
      { title: "Raised foot ring", body: "The foot ring lifts the base clear of the sink, keeping rinsed produce out of standing water while it drains." },
    ],
    specs: [
      { label: "Diameter", value: "24cm" },
      { label: "Material", value: "Brushed stainless steel" },
      { label: "Rim", value: "Rolled edge" },
      { label: "Handles", value: "Two, riveted" },
      { label: "Base", value: "Raised foot ring" },
      { label: "Drainage", value: "Fine perforations" },
    ],
    materials: ["Brushed stainless steel", "Steel rivets"],
    inBox: ["24cm stainless steel colander", "Care leaflet"],
    care: "Wash in warm soapy water and dry the rim and rivets to prevent water marks.",
  },
  "acacia-knife-block": {
    highlights: [
      { title: "Five knives covered", body: "Chef's, bread, santoku, utility and paring blades handle the usual run of prep work without reaching for extra tools." },
      { title: "Angled slots", body: "The acacia block holds each of the five knives at an angle, so blades clear the wood and handles stay within reach." },
      { title: "Riveted handles", body: "Rivets hold the handle scales to the tang and polished bolsters give the hand a defined stopping point behind the blade." },
    ],
    specs: [
      { label: "Pieces", value: "5 knives plus block" },
      { label: "Blades", value: "Stainless steel" },
      { label: "Block", value: "Grained acacia" },
      { label: "Handles", value: "Riveted, polished bolsters" },
      { label: "Slots", value: "5 angled" },
      { label: "Blade lengths", value: "20cm, 20cm, 18cm, 13cm, 9cm" },
    ],
    materials: ["Stainless steel", "Grained acacia", "Polished steel bolsters"],
    inBox: ["Acacia knife block", "Chef's, bread and santoku knives", "Utility and paring knives"],
    care: "Hand-wash the knives and wipe the acacia block with a damp cloth; do not soak either.",
  },
  "countertop-dish-rack": {
    highlights: [
      { title: "Two drying levels", body: "The upper tier holds cups and small bowls while plate slots on the lower tier keep larger items upright and separated." },
      { title: "Removable utensil cup", body: "Cutlery drains upright in a cup that lifts out for emptying and rinsing, then clips back onto the frame." },
      { title: "Tray with spout", body: "Ribbed channels carry water to a pouring spout, so the tray can be emptied into the sink without lifting the rack." },
    ],
    specs: [
      { label: "Levels", value: "Two" },
      { label: "Tray", value: "Ribbed, with pouring spout" },
      { label: "Utensil cup", value: "Removable, one" },
      { label: "Feet", value: "Four rubber feet" },
      { label: "Dimensions", value: "45 × 30 × 36cm" },
      { label: "Weight", value: "2.1kg" },
    ],
    materials: ["Coated steel wire", "Polypropylene tray", "Rubber feet"],
    inBox: ["Two-level wire dish rack", "Ribbed drip tray", "Removable utensil cup"],
    care: "Wipe the wire and tray by hand; tableware is not included with the rack.",
  },
  "bamboo-dustpan-set": {
    highlights: [
      { title: "Flexible rubber lip", body: "The rubber lip sits flush against floorboards and tiles, so dust and crumbs cross the edge instead of collecting behind it." },
      { title: "Dense brush bristles", body: "Closely packed bristles hold fine dust rather than scattering it, clearing crumbs from worktops, stair treads and hard floors in a few strokes." },
      { title: "Hanging loop storage", body: "A hanging loop keeps the set on a hook by the door or inside a cupboard, off the floor and quick to reach." },
    ],
    specs: [
      { label: "Material", value: "Bamboo with rubber lip" },
      { label: "Pieces", value: "2 (dustpan and hand brush)" },
      { label: "Bristles", value: "Dense synthetic fill" },
      { label: "Storage", value: "Hanging loop on each piece" },
      { label: "Pan width", value: "23cm" },
      { label: "Brush length", value: "27cm" },
    ],
    materials: ["Bamboo", "Natural rubber", "Synthetic bristles"],
    inBox: ["Bamboo dustpan", "Matching hand brush"],
    care: "Wipe the bamboo with a damp cloth and dry it; do not soak or machine wash.",
  },
  "refillable-soap-dispenser": {
    highlights: [
      { title: "400ml ceramic body", body: "Holds 400ml of liquid hand soap, enough for regular refilling rather than daily topping up at a busy sink." },
      { title: "Polished-metal pump", body: "The pump draws soap through a metal spout and returns to rest quietly, dispensing a measured amount with one press." },
      { title: "Screw-on collar", body: "The collar threads onto the neck, holding the pump straight and letting the bottle be opened fully for refilling." },
    ],
    specs: [
      { label: "Capacity", value: "400ml" },
      { label: "Material", value: "Ribbed ceramic, polished metal pump" },
      { label: "Finish", value: "Speckled cream glaze" },
      { label: "Closure", value: "Screw-on collar" },
      { label: "Dimensions", value: "7cm diameter, 18cm high" },
      { label: "Contents", value: "Sold empty, no soap included" },
    ],
    materials: ["Ribbed ceramic", "Polished metal", "Speckled cream glaze"],
    inBox: ["Refillable soap dispenser, 400ml", "Polished-metal pump with screw-on collar"],
    care: "Wipe the glaze and pump by hand with a damp cloth; do not machine wash.",
  },
  "rechargeable-fabric-shaver": {
    highlights: [
      { title: "Perforated steel head", body: "The perforated steel head guards the blades, lifting bobbles from the surface while keeping the weave of the fabric intact." },
      { title: "Removable lint chamber", body: "The chamber detaches for emptying between garments, so collected fluff does not build up against the blades and slow the head." },
      { title: "USB-C charging", body: "Charges over USB-C from a laptop or mains adapter, so the shaver can be topped up with a cable already to hand." },
    ],
    specs: [
      { label: "Charging", value: "USB-C rechargeable" },
      { label: "Head", value: "Perforated steel" },
      { label: "Chamber", value: "Removable lint chamber" },
      { label: "Grip", value: "Contoured, non-slip" },
      { label: "Runtime", value: "Approx. 60 minutes per charge" },
      { label: "Weight", value: "210g" },
    ],
    materials: ["Perforated steel", "ABS housing", "Rubberised grip"],
    inBox: ["Rechargeable fabric shaver", "USB-C charging cable", "Cleaning brush"],
    care: "Test a hidden area first and use a light touch on suitable knitwear only.",
  },
  "wooden-hanger-set": {
    highlights: [
      { title: "Curved shoulder profile", body: "The curved shoulders follow the line of a jacket or shirt, spreading weight across the seam so fabric holds its shape between wears." },
      { title: "Trouser bar included", body: "Each hanger carries a trouser bar below the shoulders, keeping a pair of trousers or a skirt on the same hook as the jacket." },
      { title: "Swivel hook and notches", body: "Brushed-metal hooks swivel a full turn for facing garments either way, and shoulder notches hold straps and hanging loops in place." },
    ],
    specs: [
      { label: "Pieces", value: "6 hangers" },
      { label: "Material", value: "Beechwood, brushed metal hooks" },
      { label: "Shoulders", value: "Curved, with notches" },
      { label: "Trouser bar", value: "Fixed, one per hanger" },
      { label: "Hook", value: "360-degree swivel" },
      { label: "Width", value: "44cm per hanger" },
    ],
    materials: ["Beechwood", "Brushed metal", "Natural grain finish"],
    inBox: ["6 beechwood hangers", "Care leaflet"],
    care: "Wipe the wood with a dry cloth; keep the hangers away from damp and direct heat.",
  },
  "compartment-laundry-sorter": {
    highlights: [
      { title: "Two sorted loads", body: "Two removable 40L linen bags divide lights and darks at the point of undressing, so washday starts already sorted." },
      { title: "Bags lift out", body: "Stitched carry handles let each bag come off the bamboo frame and travel to the machine on its own." },
      { title: "Steady on floors", body: "The bamboo frame stands on capped feet, keeping the base off tiles and floorboards while bags are loaded." },
    ],
    specs: [
      { label: "Capacity", value: "2 × 40L" },
      { label: "Compartments", value: "Two, open tops" },
      { label: "Frame", value: "Bamboo" },
      { label: "Bags", value: "Linen, removable" },
      { label: "Dimensions", value: "64 × 33 × 66cm" },
      { label: "Feet", value: "Capped, four" },
    ],
    materials: ["Bamboo", "Linen", "Stitched cotton webbing"],
    inBox: ["Two-compartment laundry sorter frame", "Two 40L linen bags", "Assembly fixings and key"],
    care: "Wash the linen bags cold and wipe the bamboo frame with a damp cloth, then dry.",
  },
  "rotating-spice-rack": {
    highlights: [
      { title: "Twelve refillable jars", body: "Twelve glass jars with metal screw lids hold ground and whole spices, refilled from bulk packs rather than replaced." },
      { title: "Two-tier turntable", body: "The two-tier wood-and-steel turntable spins so the back row comes forward, keeping all twelve jars within reach." },
      { title: "Labelled fronts", body: "Each jar carries a labelled front, so favourite seasonings are identified at a glance without lifting lids to check." },
    ],
    specs: [
      { label: "Jars", value: "12 refillable glass jars" },
      { label: "Lids", value: "Metal screw lids" },
      { label: "Tiers", value: "Two" },
      { label: "Jar capacity", value: "100ml each" },
      { label: "Dimensions", value: "24cm diameter, 28cm high" },
      { label: "Included", value: "Spices not included" },
    ],
    materials: ["Glass", "Metal", "Wood", "Steel"],
    inBox: ["Rotating spice rack turntable", "12 glass jars with lids", "Label sheet"],
    care: "Hand-wash the jars and lids; wipe the wood-and-steel turntable with a damp cloth and dry immediately.",
  },
  "airtight-food-container-set": {
    highlights: [
      { title: "Four graded sizes", body: "Containers of 500ml, 900ml, 1.4L and 2L cover everything from spices and seeds to flour, pasta and rice." },
      { title: "Clip-lock lids", body: "Four clips press each lid onto a silicone gasket, holding an airtight seal so dry ingredients stay dry between uses." },
      { title: "Stackable shapes", body: "Flat lids and matching footprints let the containers sit squarely on each other, keeping pantry shelves and cupboards in order." },
    ],
    specs: [
      { label: "Capacity", value: "500ml, 900ml, 1.4L, 2L" },
      { label: "Pieces", value: "4 containers with 4 lids" },
      { label: "Seal", value: "Clip-lock lid, silicone gasket" },
      { label: "Body", value: "Clear, stackable" },
      { label: "Contents", value: "Food not included" },
      { label: "Material", value: "Plastic and silicone" },
    ],
    materials: ["Clear plastic", "Silicone gasket", "Moulded clip fastenings"],
    inBox: ["4 airtight containers", "4 clip-lock lids with gaskets", "Care leaflet"],
    care: "Hand-wash the containers and lids in warm water, and remove the gaskets to dry fully.",
  },
  "woven-storage-ottoman": {
    highlights: [
      { title: "Concealed compartment", body: "The hollow base holds throws, cushion covers and everyday extras, keeping the living room floor clear without a separate basket." },
      { title: "Linen-padded lid", body: "The removable lid is padded and covered in linen, giving a seat that lifts away when the compartment is needed." },
      { title: "Low wooden feet", body: "Short wooden feet raise the woven body off the floor, easing cleaning underneath and keeping the base away from damp." },
    ],
    specs: [
      { label: "Width", value: "45cm" },
      { label: "Height", value: "42cm" },
      { label: "Lid", value: "Removable, linen-padded" },
      { label: "Feet", value: "Low wooden feet" },
      { label: "Storage", value: "Concealed internal compartment" },
      { label: "Weight", value: "6.2kg" },
    ],
    materials: ["Woven paper rope", "Linen", "Solid wood", "Foam padding"],
    inBox: ["Woven storage ottoman, 45cm", "Removable linen-padded lid", "Four wooden feet with fixings"],
    care: "Wipe the weave with a dry cloth and spot-clean the linen lid; do not machine wash.",
  },
  "digital-dehumidifier": {
    highlights: [
      { title: "12L daily extraction", body: "Rated up to 12L per day, drawing damp air from bedrooms, bathrooms and utility rooms to slow condensation on windows and walls." },
      { title: "2L tank with shut-off", body: "The 2L tank lifts out for emptying, and full-tank shut-off stops the unit once the water level reaches the limit." },
      { title: "Digital display and castors", body: "An adjustable humidity target is set on the digital display, and castors let the unit roll between rooms without lifting." },
    ],
    specs: [
      { label: "Extraction", value: "Up to 12L per day" },
      { label: "Tank", value: "2L removable" },
      { label: "Controls", value: "Digital display, adjustable humidity target" },
      { label: "Safety", value: "Full-tank shut-off" },
      { label: "Mobility", value: "Four castors" },
      { label: "Power", value: "200W" },
    ],
    materials: ["ABS plastic housing", "Powder-coated steel", "Nylon castors"],
    inBox: ["Digital dehumidifier", "2L removable tank", "Instruction manual"],
    care: "Empty and rinse the 2L tank regularly, and unplug the unit before cleaning it.",
  },
  "ribbed-ceramic-diffuser": {
    highlights: [
      { title: "Fluted ceramic cover", body: "The ribbed sage ceramic cover lifts away for filling, and hides the working parts so the unit reads as an ornament." },
      { title: "150ml ultrasonic mist", body: "Ultrasonic plate breaks water and a few drops of essential oil into a cool mist, so no heat is applied to the oil." },
      { title: "Automatic shut-off", body: "The diffuser stops on its own when the 150ml tank runs empty, so it can be left running overnight or during the day." },
    ],
    specs: [
      { label: "Capacity", value: "150ml" },
      { label: "Type", value: "Ultrasonic aroma diffuser" },
      { label: "Material", value: "Ceramic cover, wood-grain base" },
      { label: "Finish", value: "Fluted sage" },
      { label: "Safety", value: "Automatic shut-off when empty" },
      { label: "Runtime", value: "Up to 6 hours" },
    ],
    materials: ["Fluted sage ceramic", "Wood-grain plastic", "ABS water tank"],
    inBox: ["Ribbed ceramic diffuser, 150ml", "USB power adapter", "Measuring cup", "Instruction leaflet"],
    care: "Use only suitable essential oil, not included, and wipe the tank dry after each use.",
  },
  "adjustable-reading-lamp": {
    highlights: [
      { title: "Articulated arm and pivots", body: "Tension springs hold each position once set, and the adjustable pivots move the head over a book, desk or bedside shelf." },
      { title: "Warm-white diffuser", body: "The LED sits behind a diffuser, softening the beam into a focused pool of light without a visible bright point." },
      { title: "Weighted base", body: "The base counterbalances the arm at full reach, so the lamp stays put on a desk or side table." },
    ],
    specs: [
      { label: "Finish", value: "Cream" },
      { label: "Light source", value: "Warm-white LED with diffuser" },
      { label: "Adjustment", value: "Tension springs, adjustable pivots" },
      { label: "Base", value: "Weighted, 16cm diameter" },
      { label: "Cord", value: "Fabric-wrapped, 1.8m" },
      { label: "Reach", value: "Up to 55cm from base" },
    ],
    materials: ["Powder-coated steel", "Weighted cast iron", "Fabric-wrapped cable", "Frosted acrylic diffuser"],
    inBox: ["Adjustable reading lamp", "Fabric-wrapped cord, fitted", "Instruction leaflet"],
    care: "Wipe the shade and base with a dry cloth; unplug before cleaning and keep the cord dry.",
  },
  "sage-air-fryer": {
    highlights: [
      { title: "5L basket capacity", body: "The 5L basket holds enough for two to four portions, so a main course cooks in one batch without refilling." },
      { title: "Temperature to 200°C", body: "Adjustable heat up to 200°C covers reheating, roasting vegetables and crisping chips, with settings held steady through the cooking time." },
      { title: "Removable non-stick basket", body: "The basket lifts out for shaking or serving, and the non-stick coating releases food without scraping or added oil." },
    ],
    specs: [
      { label: "Capacity", value: "5L" },
      { label: "Temperature", value: "Adjustable up to 200°C" },
      { label: "Timer", value: "Digital, up to 60 minutes" },
      { label: "Basket", value: "Removable, non-stick coated" },
      { label: "Power", value: "1,500W" },
      { label: "Cord", value: "1.1m" },
    ],
    materials: ["Non-stick coated aluminium", "Heat-resistant plastic housing", "Stainless steel trim"],
    inBox: ["Sage Air Fryer", "Removable non-stick basket", "Instruction and recipe booklet"],
    care: "Hand-wash the removable basket with warm soapy water and wipe the housing with a damp cloth.",
  },
  "cream-electric-kettle": {
    highlights: [
      { title: "1.7L stainless-steel interior", body: "Holds 1.7L, enough for about seven mugs, with a stainless-steel interior that keeps the water clear of plastic taste." },
      { title: "360° base", body: "The kettle lifts and returns from any angle, so it suits left- or right-handed pouring and tight counter corners." },
      { title: "Automatic shut-off", body: "Power cuts once the water reaches the boil, and the easy-pour spout directs a steady stream into cups or cafetières." },
    ],
    specs: [
      { label: "Capacity", value: "1.7L" },
      { label: "Power", value: "2,200W" },
      { label: "Interior", value: "Stainless steel" },
      { label: "Base", value: "360° cordless" },
      { label: "Safety", value: "Automatic shut-off, boil-dry cut-out" },
      { label: "Cord", value: "75cm, stores in base" },
    ],
    materials: ["Stainless steel", "Cream painted steel", "Heat-resistant polypropylene"],
    inBox: ["Cream electric kettle, 1.7L", "360° power base", "Instruction leaflet"],
    care: "Wipe the exterior with a damp cloth, descale monthly, and never immerse the kettle or base in water.",
  },
  "two-slice-toaster": {
    highlights: [
      { title: "Wide slots for sourdough", body: "The slots take thick-cut sourdough and bloomer slices, so hand-cut bread sits level without wedging or catching on the way down." },
      { title: "Six browning settings", body: "A numbered dial moves from light to dark across six steps, letting the same setting be repeated from one morning to the next." },
      { title: "Removable crumb tray", body: "The tray slides out from the base so crumbs can be tipped away and the toaster wiped without turning it upside down." },
    ],
    specs: [
      { label: "Capacity", value: "Two slices, wide slots" },
      { label: "Settings", value: "Six browning levels" },
      { label: "Crumb tray", value: "Removable, slide-out" },
      { label: "Finish", value: "Warm cream, brushed-metal details" },
      { label: "Power", value: "900W" },
      { label: "Cord", value: "0.8m, stores under base" },
    ],
    materials: ["Warm cream painted steel", "Brushed metal", "Heat-resistant plastic", "Chrome wire elements"],
    inBox: ["Two-slice toaster", "Removable crumb tray", "Instruction leaflet"],
    care: "Unplug and cool before cleaning; wipe the body and hand-wash the crumb tray only.",
  },
  "compact-espresso-machine": {
    highlights: [
      { title: "15-bar pump pressure", body: "The 15-bar pump forces water through the ground coffee at a steady rate, drawing out a consistent espresso shot with crema." },
      { title: "Steam wand for milk", body: "The steam wand froths milk in a jug for cappuccino or flat white, and swings aside for cleaning after each use." },
      { title: "1.2L removable tank", body: "The 1.2L water tank lifts out for filling at the tap, holding enough for several shots before a refill is needed." },
    ],
    specs: [
      { label: "Pressure", value: "15-bar pump" },
      { label: "Tank", value: "1.2L, removable" },
      { label: "Power", value: "1,250W" },
      { label: "Dimensions", value: "19 × 29 × 30cm" },
      { label: "Weight", value: "4.1kg" },
      { label: "Cord", value: "1m" },
    ],
    materials: ["Brushed stainless steel", "ABS plastic", "Chrome-plated brass", "BPA-free plastic"],
    inBox: ["Compact espresso machine", "Portafilter with two filter baskets", "Tamper and measuring scoop", "Instruction manual"],
    care: "Hand-wash the drip tray, portafilter and baskets; purge the steam wand after every milk use.",
  },
  "glass-jug-blender": {
    highlights: [
      { title: "1.5L glass jug", body: "The 1.5L glass jug holds enough for several servings, resists staining from sauces, and shows the blend level while it runs." },
      { title: "Stainless-steel blades", body: "Stainless-steel blades break down fruit, herbs and cooked vegetables, so smoothies and soups reach an even texture without repeated stops." },
      { title: "Three speeds and pulse", body: "Three speeds cover slow mixing through to fine blending, while pulse control gives short bursts for coarse chopping and scraping down." },
    ],
    specs: [
      { label: "Capacity", value: "1.5L" },
      { label: "Jug", value: "Glass" },
      { label: "Blades", value: "Stainless steel" },
      { label: "Settings", value: "Three speeds with pulse" },
      { label: "Power", value: "500W" },
      { label: "Cord", value: "1.2m" },
    ],
    materials: ["Glass", "Stainless steel", "Moulded plastic", "Silicone seal"],
    inBox: ["Glass jug blender", "1.5L glass jug with lid", "Spare silicone seal", "Instruction leaflet"],
    care: "Allow soups to cool before blending, and wash the jug and blades by hand.",
  },
  "cast-iron-casserole": {
    highlights: [
      { title: "Four litres of space", body: "The 4L body holds a joint with vegetables or a stew for six, with room left below the rim." },
      { title: "Close-fitting lid", body: "The lid sits flush against the rim, holding steam and moisture inside through long, slow cooking on a low heat." },
      { title: "Generous side handles", body: "Two wide loop handles give a firm grip with oven gloves, so the casserole moves from hob to table in one lift." },
    ],
    specs: [
      { label: "Capacity", value: "4L" },
      { label: "Material", value: "Enamelled cast iron" },
      { label: "Finish", value: "Warm terracotta" },
      { label: "Lid", value: "Close-fitting, cast iron" },
      { label: "Handles", value: "Two integral loop handles" },
      { label: "Diameter", value: "24cm" },
    ],
    materials: ["Enamelled cast iron", "Vitreous enamel", "Sand-cast iron lid"],
    inBox: ["Cast iron casserole, 4L", "Cast iron lid", "Care and use leaflet"],
    care: "Hand-wash in warm soapy water, dry thoroughly, and avoid metal tools on the enamel.",
  },
  "ceramic-frying-pan": {
    highlights: [
      { title: "Smooth ceramic surface", body: "The ceramic cooking surface releases eggs, fish and pancakes with little oil, and wipes clean with a soft cloth." },
      { title: "28cm cooking area", body: "A 28cm base holds two portions at once, with room to turn food without crowding the pan." },
      { title: "Wood handle", body: "The wood handle stays comfortable in the hand during everyday hob cooking and gives a steady grip when lifting." },
    ],
    specs: [
      { label: "Diameter", value: "28cm" },
      { label: "Surface", value: "Ceramic non-stick" },
      { label: "Exterior", value: "Sage" },
      { label: "Handle", value: "Wood" },
      { label: "Use", value: "Everyday hob cooking" },
      { label: "Cleaning", value: "Hand-wash only" },
    ],
    materials: ["Ceramic coating", "Aluminium body", "Sage enamel exterior", "Wood"],
    inBox: ["28cm ceramic frying pan", "Care and use leaflet"],
    care: "Hand-wash with warm water and a soft sponge, then dry before storing; do not use dishwasher.",
  },
  "stainless-saucepan": {
    highlights: [
      { title: "Layered base", body: "The layered base spreads heat across the full width of the pan, reducing hot spots when reducing sauces or simmering grains." },
      { title: "Fitted lid", body: "The lid sits flush on the rim to hold steam and heat, which shortens boiling time and keeps grains from drying out." },
      { title: "Long handle", body: "The long handle keeps the grip away from the burner and gives control when pouring smaller portions from the 2L body." },
    ],
    specs: [
      { label: "Capacity", value: "2L" },
      { label: "Material", value: "Stainless steel" },
      { label: "Base", value: "Layered, even heating" },
      { label: "Lid", value: "Fitted stainless steel" },
      { label: "Handle", value: "Long, riveted" },
      { label: "Diameter", value: "16cm" },
    ],
    materials: ["Stainless steel", "Aluminium core", "Stainless steel rivets"],
    inBox: ["2L stainless-steel saucepan", "Fitted lid", "Care leaflet"],
    care: "Wash by hand with warm water and a soft cloth, then dry to prevent water marks.",
  },
  "bamboo-chopping-board": {
    highlights: [
      { title: "Juice groove", body: "A channel runs around the edge to hold juices from roast meat, fruit or tomatoes, keeping the worktop clear." },
      { title: "Carry handle", body: "A cut-out handle at one end makes the board easy to lift and carry to the table for serving." },
      { title: "40 × 28cm surface", body: "Enough room to break down a chicken or line up chopped vegetables, while still fitting most worktops and sink basins." },
    ],
    specs: [
      { label: "Dimensions", value: "40 × 28cm" },
      { label: "Thickness", value: "1.8cm" },
      { label: "Material", value: "Bamboo" },
      { label: "Features", value: "Juice groove, carry handle" },
      { label: "Weight", value: "1.1kg" },
      { label: "Care", value: "Hand-wash, dry upright" },
    ],
    materials: ["Bamboo", "Food-safe adhesive", "Natural mineral oil finish"],
    inBox: ["Bamboo chopping board 40 × 28cm", "Care and oiling leaflet"],
    care: "Hand-wash with warm water, dry upright, and oil occasionally; do not soak or machine wash.",
  },
  "stoneware-dinner-set": {
    highlights: [
      { title: "Twelve pieces for four", body: "Four dinner plates, four bowls and four mugs, enough to lay a table for four without mixing patterns." },
      { title: "Warm cream glaze", body: "The softly glazed finish sits matt to the eye and smooth to the touch, hiding light marks from daily use." },
      { title: "Stacks in a cupboard", body: "Plates and bowls nest in even stacks, so the full set fits one shelf beside the mugs." },
    ],
    specs: [
      { label: "Pieces", value: "12, service for four" },
      { label: "Material", value: "Cream stoneware, softly glazed" },
      { label: "Plates", value: "4 dinner plates, 27cm" },
      { label: "Bowls", value: "4 bowls, 16cm, 600ml" },
      { label: "Mugs", value: "4 mugs, 350ml" },
      { label: "Weight", value: "6.2kg, full set" },
    ],
    materials: ["Cream stoneware", "Soft glaze"],
    inBox: ["Stoneware dinner set, 12 pieces", "Card dividers between plates", "Care leaflet"],
    care: "Wash in warm soapy water and dry before stacking; avoid sudden temperature changes that can crack the glaze.",
  },
  "cordless-stick-vacuum": {
    highlights: [
      { title: "Motorised floor head", body: "The driven brush roll turns as it moves, lifting dust and hair from hard floors and short-pile carpet in one pass." },
      { title: "Forty minutes cordless", body: "A single charge gives up to 40 minutes of cleaning in standard mode, enough for most flats without returning to the dock." },
      { title: "Washable filter", body: "The filter rinses under the tap and returns to the unit once dry, so no replacement cartridges are needed between cleans." },
    ],
    specs: [
      { label: "Runtime", value: "Up to 40 minutes, standard mode" },
      { label: "Filter", value: "Washable, removable" },
      { label: "Dust cup", value: "Removable, 0.6L" },
      { label: "Floor head", value: "Motorised brush roll" },
      { label: "Weight", value: "2.6kg assembled" },
      { label: "Charging", value: "Approximately 4 hours" },
    ],
    materials: ["ABS plastic", "Aluminium tube", "Nylon brush bristles"],
    inBox: ["Cordless stick vacuum", "Motorised floor head", "Charger and wall bracket", "Crevice tool"],
    care: "Rinse the washable filter and dust cup in cold water, then dry fully before refitting.",
  },
  "robot-vacuum": {
    highlights: [
      { title: "Room mapping", body: "The vacuum builds a map of each room as it works, so it covers floors in ordered rows rather than random passes." },
      { title: "Edge brushes", body: "Side brushes sweep dust from skirting boards and corners into the suction path, where a straight-line head alone would miss it." },
      { title: "Automatic dock return", body: "When the battery runs low or a run ends, the unit returns to its charging dock without being carried back." },
    ],
    specs: [
      { label: "Navigation", value: "Room mapping" },
      { label: "Brushes", value: "Two edge brushes, one roller" },
      { label: "Docking", value: "Automatic return to charging dock" },
      { label: "Height", value: "7.6cm low profile" },
      { label: "Runtime", value: "Up to 110 minutes" },
      { label: "Dust bin", value: "0.4L, removable" },
    ],
    materials: ["ABS plastic", "Nylon bristles", "Rubber roller", "Washable mesh filter"],
    inBox: ["Robot vacuum", "Charging dock and adapter", "Two spare edge brushes", "Washable filter"],
    care: "Empty the 0.4L bin after each run and rinse the filter, leaving it fully dry before refitting.",
  },
  "spray-mop": {
    highlights: [
      { title: "500ml refillable bottle", body: "The 500ml bottle detaches for refilling with water or a chosen floor solution, so no single-use cartridges are needed." },
      { title: "Swivel head", body: "The head pivots to follow the handle, reaching under low furniture and along skirting boards without lifting the mop." },
      { title: "Washable microfibre pad", body: "The microfibre pad lifts dust and light marks from sealed hard floors, then goes in the wash and back on the head." },
    ],
    specs: [
      { label: "Capacity", value: "500ml refillable bottle" },
      { label: "Head", value: "Swivel, 28cm wide" },
      { label: "Pad", value: "Washable microfibre, 1 included" },
      { label: "Surfaces", value: "Sealed hard floors" },
      { label: "Length", value: "125cm handle" },
      { label: "Weight", value: "1.1kg empty" },
    ],
    materials: ["Microfibre", "Coated aluminium", "Moulded polypropylene"],
    inBox: ["Refillable spray mop", "500ml bottle", "Washable microfibre pad"],
    care: "Use on sealed hard floors only; machine-wash the microfibre pad and refill the bottle as needed.",
  },
  "steam-cleaner": {
    highlights: [
      { title: "One litre tank", body: "The 1L tank holds enough water for a session of spot cleaning, then refills from the tap between tasks." },
      { title: "Flexible hose reach", body: "The flexible hose directs steam into grout lines, taps and corners while the body stays resting on the floor." },
      { title: "Detail nozzle work", body: "The detail nozzle concentrates steam on a small area to loosen grime on sealed tiles without detergent." },
    ],
    specs: [
      { label: "Capacity", value: "1L" },
      { label: "Power", value: "1,200W" },
      { label: "Attachments", value: "Flexible hose, detail nozzle" },
      { label: "Detergent", value: "Not required" },
      { label: "Surfaces", value: "Sealed tiles, suitable hard surfaces" },
      { label: "Cord", value: "3m" },
    ],
    materials: ["Moulded polypropylene", "Stainless steel boiler", "Silicone hose"],
    inBox: ["Compact steam cleaner", "Flexible hose", "Detail nozzle", "Filling jug"],
    care: "Empty the 1L tank after use and avoid unsealed tiles, untreated wood and other porous surfaces.",
  },
  "pedal-bin": {
    highlights: [
      { title: "Soft-closing lid", body: "The lid lowers slowly and quietly rather than dropping shut, which keeps noise down in open-plan kitchens and utility rooms." },
      { title: "Foot pedal opening", body: "The pedal lifts the lid so hands stay free while scraping plates or carrying waste across the room." },
      { title: "Removable inner bucket", body: "The inner bucket lifts out for emptying and rinsing, and holds the liner edges out of sight inside the body." },
    ],
    specs: [
      { label: "Capacity", value: "30L" },
      { label: "Finish", value: "Cream" },
      { label: "Opening", value: "Foot pedal" },
      { label: "Lid", value: "Soft-closing" },
      { label: "Liner", value: "Removable inner bucket" },
      { label: "Dimensions", value: "40 × 30 × 66cm" },
    ],
    materials: ["Powder-coated steel", "Cream painted finish", "Moulded plastic bucket"],
    inBox: ["Soft-close pedal bin, 30L", "Removable inner bucket", "Instruction leaflet"],
    care: "Wipe the body with a damp cloth and rinse the inner bucket by hand, then dry.",
  },
  "steam-iron": {
    highlights: [
      { title: "2,400W heat-up", body: "The 2,400W element brings the soleplate to temperature quickly, so a basket of shirts can be worked through in one session." },
      { title: "Pointed soleplate", body: "The tapered tip reaches under buttons, between pleats and along collar seams without needing the garment to be repositioned." },
      { title: "Variable steam control", body: "Steam output adjusts from dry to full, and the heat dial follows the garment's care label, from synthetics through to linen." },
    ],
    specs: [
      { label: "Power", value: "2,400W" },
      { label: "Soleplate", value: "Pointed, stainless steel" },
      { label: "Steam", value: "Variable, dry to full" },
      { label: "Tank", value: "300ml, easy-fill opening" },
      { label: "Settings", value: "Adjustable heat dial" },
      { label: "Cord", value: "2m, 360° swivel" },
    ],
    materials: ["Stainless steel", "Heat-resistant polypropylene", "Silicone seals"],
    inBox: ["Everyday Steam Iron", "Filling beaker", "Instruction leaflet"],
    care: "Set the heat dial to match the garment's care label, and empty the tank after use.",
  },
  "handheld-garment-steamer": {
    highlights: [
      { title: "Removable 250ml tank", body: "The 250ml water tank lifts off for filling at the tap and clips back in place, so refills take seconds." },
      { title: "Steams on the hanger", body: "Creases soften on hanging garments, which removes the need to set up a board for a shirt or a dress." },
      { title: "Comfortable grip", body: "The shaped handle keeps the weight over the wrist, so the head can be held against fabric for longer runs." },
    ],
    specs: [
      { label: "Tank", value: "250ml, removable" },
      { label: "Power", value: "1,200W" },
      { label: "Heat-up", value: "About 40 seconds" },
      { label: "Runtime", value: "Around 10 minutes per tank" },
      { label: "Cord", value: "2.5m" },
      { label: "Weight", value: "0.8kg empty" },
    ],
    materials: ["Heat-resistant polypropylene", "Stainless steel soleplate", "Silicone seals"],
    inBox: ["Handheld garment steamer", "Removable 250ml water tank", "Filling cup", "Instruction leaflet"],
    care: "Empty the tank after each use and wipe the soleplate once the unit has cooled.",
  },
  "folding-drying-rack": {
    highlights: [
      { title: "18m of hanging space", body: "Fold-out wings open on both sides to give 18m of line, enough for a full machine load of mixed washing." },
      { title: "Folds flat", body: "The frame closes to a flat panel between wash days, so it stores upright against a wall or behind a door." },
      { title: "Capped feet", body: "Each foot carries a moulded cap that protects floorboards and tiles and keeps the frame steady on smooth surfaces." },
    ],
    specs: [
      { label: "Hanging space", value: "18m" },
      { label: "Type", value: "Freestanding, fold-out wings" },
      { label: "Open size", value: "180 × 55 × 105cm" },
      { label: "Folded depth", value: "7cm" },
      { label: "Weight", value: "4.2kg" },
      { label: "Feet", value: "Capped, floor protecting" },
    ],
    materials: ["Powder-coated steel", "Epoxy-coated wire", "Moulded plastic caps"],
    inBox: ["Folding drying rack", "Four spare foot caps", "Assembly and folding guide"],
    care: "Wipe the frame with a damp cloth and fold flat when dry to prevent standing moisture.",
  },
  "woven-laundry-hamper": {
    highlights: [
      { title: "Sixty litres, lid on", body: "The 60L basket holds several days of washing, and the fitted lid keeps the pile out of sight between loads." },
      { title: "Removable cotton liner", body: "The cotton liner lifts out with the load, so clothing travels to the machine without the basket leaving its corner." },
      { title: "Handles on both sides", body: "Carry handles set into the weave allow the hamper to be moved between bedroom, bathroom and utility room with two hands." },
    ],
    specs: [
      { label: "Capacity", value: "60L" },
      { label: "Lid", value: "Fitted, removable" },
      { label: "Liner", value: "Removable cotton" },
      { label: "Handles", value: "Two woven side handles" },
      { label: "Dimensions", value: "40 × 40 × 60cm" },
      { label: "Finish", value: "Natural woven texture" },
    ],
    materials: ["Woven paper rope", "Steel wire frame", "Cotton liner"],
    inBox: ["Woven laundry hamper", "Fitted lid", "Removable cotton liner"],
    care: "Machine-wash the cotton liner at 30C; wipe the woven basket with a barely damp cloth only.",
  },
  "ironing-board": {
    highlights: [
      { title: "Full-size board surface", body: "The 110 × 34cm padded top takes shirts, sheets and trousers flat, so fewer repositioning moves are needed between passes of the iron." },
      { title: "Adjustable working height", body: "The frame locks at several heights, letting the board sit level with the hip whether ironing standing or seated at a chair." },
      { title: "Folds away flat", body: "The legs collapse against the underside so the board stands in a cupboard gap or behind a door once the last shirt is done." },
    ],
    specs: [
      { label: "Dimensions", value: "110 × 34cm board" },
      { label: "Height", value: "Adjustable, 75 to 90cm" },
      { label: "Cover", value: "Cotton, padded underlay" },
      { label: "Iron rest", value: "Metal, fixed at end" },
      { label: "Frame", value: "Folding steel legs" },
      { label: "Weight", value: "4.2kg" },
    ],
    materials: ["Cotton cover", "Foam padding", "Powder-coated steel", "Metal iron rest"],
    inBox: ["Folding ironing board", "Cotton cover, fitted", "Metal iron rest"],
    care: "Remove the cotton cover and wash it separately; wipe the metal frame and iron rest dry.",
  },
  "glass-storage-jars": {
    highlights: [
      { title: "Three graded sizes", body: "Jars in 600ml, 900ml and 1.2L hold small spices through to flour or pasta, so staples stay grouped by volume." },
      { title: "Silicone-sealed bamboo lids", body: "Each bamboo lid carries a silicone seal that closes against the rim, keeping dry ingredients from drawing in damp air." },
      { title: "Clear glass walls", body: "Contents stay visible from the shelf, so levels can be checked and refills judged without opening or relabelling the jars." },
    ],
    specs: [
      { label: "Capacity", value: "600ml, 900ml, 1.2L" },
      { label: "Pieces", value: "3 jars with lids" },
      { label: "Material", value: "Clear glass, bamboo, silicone" },
      { label: "Lid", value: "Bamboo with silicone seal" },
      { label: "Contents", value: "Dry ingredients" },
      { label: "Finish", value: "Untreated bamboo, plain glass" },
    ],
    materials: ["Clear glass", "Bamboo", "Silicone"],
    inBox: ["3 glass storage jars", "3 bamboo lids with seals"],
    care: "Hand-wash the bamboo lids and silicone seals, then dry fully before refitting them to the jars.",
  },
  "bamboo-bread-box": {
    highlights: [
      { title: "Roll-top door", body: "The smooth roll-top slides up and back into the box, so the door never swings out over the worktop." },
      { title: "Easy-grip handle", body: "A shaped handle on the door front gives a steady hold, letting the box open with one hand while carrying bread in the other." },
      { title: "Loaves and pastries together", body: "One compartment holds a standard loaf alongside rolls or pastries, keeping baked goods in a single place rather than spread across the surface." },
    ],
    specs: [
      { label: "Material", value: "Bamboo" },
      { label: "Door", value: "Roll-top with easy-grip handle" },
      { label: "Dimensions", value: "38 × 24 × 20cm" },
      { label: "Weight", value: "2.1kg" },
      { label: "Capacity", value: "One large loaf plus pastries" },
      { label: "Finish", value: "Natural, food-safe oil" },
    ],
    materials: ["Bamboo", "Food-safe oil finish", "Bamboo slat roll-top"],
    inBox: ["Bamboo bread box", "Roll-top door, fitted", "Care and assembly leaflet"],
    care: "Wipe the bamboo with a damp cloth and dry at once; do not soak or dishwash.",
  },
  "stackable-storage-baskets": {
    highlights: [
      { title: "Ventilated sides", body: "Open slots on all four sides let air move through, which keeps stored linen, root vegetables and bathroom stock from turning musty." },
      { title: "Stackable rims", body: "The moulded rim locates into the base above, so two or three baskets hold their position in a cupboard or on a shelf." },
      { title: "Carry handles", body: "Cut-out handles at each end let a loaded basket be lifted from a high shelf and carried to the worktop with both hands." },
    ],
    specs: [
      { label: "Pieces", value: "Set of three baskets" },
      { label: "Dimensions", value: "30 × 22 × 14cm each" },
      { label: "Material", value: "Polypropylene" },
      { label: "Features", value: "Ventilated sides, stackable rims" },
      { label: "Handles", value: "Integrated cut-out, two per basket" },
      { label: "Weight", value: "380g each" },
    ],
    materials: ["Polypropylene", "Moulded plastic rim"],
    inBox: ["Three stackable storage baskets", "Care leaflet"],
    care: "Wipe with a damp cloth and mild detergent; avoid abrasive scourers and prolonged direct heat.",
  },
  "modular-drawer-organiser": {
    highlights: [
      { title: "Five complementary sizes", body: "Five open trays in different footprints, so cutlery, utensils, pens or small odds and ends each get a space that fits." },
      { title: "Arrange to suit", body: "The trays sit loose rather than fixed, so they can be shifted, stacked side by side or split across two drawers." },
      { title: "Open tops", body: "Each tray stays open at the top, keeping contents visible and within reach when the drawer is pulled out." },
    ],
    specs: [
      { label: "Pieces", value: "5 open trays" },
      { label: "Material", value: "Bamboo" },
      { label: "Sizes", value: "Complementary, four footprints" },
      { label: "Dimensions", value: "Largest tray 30 × 15 × 5cm" },
      { label: "Finish", value: "Natural, lightly sanded" },
      { label: "Weight", value: "900g, full set" },
    ],
    materials: ["Bamboo", "Natural oil finish"],
    inBox: ["5 bamboo trays", "Care leaflet"],
    care: "Wipe with a damp cloth and dry at once; do not soak or machine wash.",
  },
  "kitchen-storage-trolley": {
    highlights: [
      { title: "Three tiers, slim frame", body: "Three open tiers hold kitchen supplies in one narrow footprint, so the trolley fits between a worktop and a wall." },
      { title: "Raised tray edges", body: "Each tier has raised edges that keep jars, packets and bottles from sliding off while the trolley is moved." },
      { title: "Handle and four castors", body: "A push handle and four castors let the loaded trolley be wheeled out for use, then returned out of the way." },
    ],
    specs: [
      { label: "Tiers", value: "Three, raised edges" },
      { label: "Castors", value: "Four" },
      { label: "Handle", value: "Push handle" },
      { label: "Material", value: "Powder-coated steel" },
      { label: "Dimensions", value: "30 × 42 × 78cm" },
      { label: "Weight", value: "4.2kg" },
    ],
    materials: ["Powder-coated steel", "Steel wire", "Nylon castors"],
    inBox: ["Three-tier storage trolley", "Four castors", "Assembly hardware and key"],
    care: "Wipe the frame and trays with a damp cloth and dry before loading.",
  },
  "hepa-air-purifier": {
    highlights: [
      { title: "Replaceable HEPA filter", body: "The HEPA filter traps fine dust, pollen and smoke particles, and lifts out for replacement without tools when airflow drops." },
      { title: "Three fan speeds", body: "Three fan speeds cover quiet overnight running through to faster clearing after cooking, cleaning or opening windows onto a busy street." },
      { title: "Dimmable status display", body: "The status display dims or switches off, so filter and speed indicators stay readable by day and unobtrusive in a dark bedroom." },
    ],
    specs: [
      { label: "Coverage", value: "Rooms up to 25m²" },
      { label: "Filter", value: "Replaceable HEPA filter" },
      { label: "Settings", value: "Three fan speeds" },
      { label: "Display", value: "Dimmable status display" },
      { label: "Power", value: "32W at top speed" },
      { label: "Dimensions", value: "22 × 22 × 38cm" },
    ],
    materials: ["ABS plastic", "Glass-fibre HEPA media", "Powder-coated steel grille"],
    inBox: ["HEPA air purifier", "One HEPA filter, fitted", "Power cable", "Instruction leaflet"],
    care: "Vacuum the intake grille monthly and replace the HEPA filter rather than washing it.",
  },
  "oscillating-table-fan": {
    highlights: [
      { title: "Three speed settings", body: "A rotary control steps through three speeds, from a low background draught to a stronger flow for warm afternoons." },
      { title: "Oscillation and tilt", body: "Side-to-side oscillation spreads air across a room, while the adjustable tilt directs the breeze up towards a seated head or down over a desk." },
      { title: "Weighted base", body: "The base holds the 30cm fan in place through full oscillation, so the head stays level on a desk or shelf." },
    ],
    specs: [
      { label: "Diameter", value: "30cm" },
      { label: "Settings", value: "Three speeds" },
      { label: "Movement", value: "Oscillation and adjustable tilt" },
      { label: "Finish", value: "Sage" },
      { label: "Power", value: "40W" },
      { label: "Cord", value: "1.8m" },
    ],
    materials: ["Moulded ABS", "Powder-coated steel", "Weighted base"],
    inBox: ["Oscillating table fan", "Front and rear grille", "Instruction leaflet"],
    care: "Unplug the fan before cleaning, and wipe the grille and housing with a dry cloth.",
  },
  "ceramic-space-heater": {
    highlights: [
      { title: "Two heat settings", body: "Choose between low and high output from the 1,500W ceramic element, so a small room can be warmed or held steady." },
      { title: "Tip-over protection", body: "An internal switch cuts power if the heater is knocked from upright, which limits risk on a clear, level floor." },
      { title: "Carry handle", body: "A moulded handle on the housing allows the heater to be lifted and moved between rooms between periods of use." },
    ],
    specs: [
      { label: "Power", value: "1,500W" },
      { label: "Settings", value: "Two heat settings" },
      { label: "Safety", value: "Tip-over protection" },
      { label: "Handle", value: "Integrated carry handle" },
      { label: "Dimensions", value: "17 × 15 × 25cm" },
      { label: "Cord", value: "1.8m" },
    ],
    materials: ["Moulded ABS housing", "Ceramic heating element", "Steel front grille"],
    inBox: ["Ceramic space heater", "Instruction leaflet", "Safety notice"],
    care: "Use only under supervision on a clear, level floor, and unplug before wiping the housing.",
  },
  "ultrasonic-humidifier": {
    highlights: [
      { title: "Adjustable mist output", body: "A single dial raises or lowers the cool-mist rate, so a small bedside table or a desk can be set to suit the room." },
      { title: "Easy-clean tank", body: "The 2L tank has a wide opening, letting a hand and cloth reach the base and sides for regular descaling and rinsing." },
      { title: "Automatic shut-off", body: "The unit stops when the tank runs empty, so it can be left running overnight without watching the water level." },
    ],
    specs: [
      { label: "Capacity", value: "2L tank" },
      { label: "Mist", value: "Cool mist, ultrasonic" },
      { label: "Settings", value: "Adjustable output dial" },
      { label: "Safety", value: "Automatic shut-off when empty" },
      { label: "Noise", value: "Around 30dB" },
      { label: "Cord", value: "1.5m" },
    ],
    materials: ["ABS plastic", "Polypropylene tank", "Silicone seal"],
    inBox: ["Ultrasonic humidifier, 2L", "Power adapter with 1.5m cord", "Cleaning brush", "Instruction leaflet"],
    care: "Unplug before filling, empty the tank after each use and wipe it dry.",
  },
  "dome-table-lamp": {
    highlights: [
      { title: "Sculptural terracotta dome", body: "The dome shade is formed in terracotta, so the light falls downward in a soft pool rather than across the whole room." },
      { title: "Warm-white LED", body: "A warm-white LED sits inside the dome, giving steady light for reading corners and bedside tables without a harsh edge." },
      { title: "In-line switch", body: "The switch sits on the cord within reach of a chair or bed, so the lamp can be turned off without standing up." },
    ],
    specs: [
      { label: "Light source", value: "Warm-white LED, integrated" },
      { label: "Switch", value: "In-line cord switch" },
      { label: "Material", value: "Terracotta dome shade" },
      { label: "Dimensions", value: "24cm diameter, 22cm high" },
      { label: "Cord", value: "1.8m, textile-covered" },
      { label: "Power", value: "6W" },
    ],
    materials: ["Terracotta", "Powder-coated steel", "Textile-covered cable"],
    inBox: ["Dome table lamp", "In-line switch cord, fitted", "Care and safety leaflet"],
    care: "Unplug before cleaning and wipe the terracotta with a dry cloth; do not immerse in water.",
  },
};

export async function getProductDetails(id: string): Promise<ProductDetails | undefined> {
  return sheets[id];
}
