# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
language: en-US
reviews:
  profile: assertive
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!bun.lock"
    - "!drizzle/meta/**"
  tools:
    eslint:
      enabled: true
